name: eShopOnWeb Build and Test

on: 
  push:
    branches: 
      - feature/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build ./src/Web/Web.csproj --configuration Release
    - name: Publish with dotnet
      run: dotnet publish ./src/Web/Web.csproj -c Release -o  ./eShopOnWeb

       # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'devsum-github'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: './eShopOnWeb'